spring:
  profiles:
    include: oauth
  session:
    store-type: jdbc
  h2:
    console:
      enabled: true

  jpa:
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
