spring:
  profiles:
    include: oauth
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  session:
    store-type: jdbc

